spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    com.github.ratel: DEBUG
    org.springframework.web: INFO
app:
  api:
    url: https://v6.exchangerate-api.com/v6/
    key: 6933516f73f2016658690a3a
    actual: /latest/